version: '3.9'
name: my_docker_project

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    configs:
      - source: nginx_default_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my_network
    restart: always
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  php:
    image: php:7.4-fpm
    container_name: php_container
    volumes:
      - ./nginx/html:/var/www/html
    networks:
      - my_network
    restart: always
    environment:
      PHP_MEMORY_LIMIT: 256M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   
    networks:
      - my_network
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: {} 
configs:
  nginx_default_config:
    file: ./nginx/conf/default.conf
